### PR TITLE
Added AI Apps section in Articles

### PR DESCRIPTION
**Pull request by dev-aritra**
:pencil2: **Section**:  Articles

By sending this pull request to contribute I verify that I adhere to the Xamarin Universal Library guidelines

- [x] The pull request adheres to the repository's `Code of Conduct`.
- [x] I have followed the section's `Contributing Guidelines`.
- [x] I understand, `Titles` should be capitalized. I have checked the grammar.
- [x] I have searched for previous suggestions before making this new one, as mine could be a duplicate.
- [x] I understand, my contribution may be removed at any time if any of these guidelines are broken.
- [x] The submitted contribution is not owned by a company which sole purpose it is to advertise a product of product line.

### CODE REVIEW

**Review by yauhenipakala — COMMENTED** [review]
Thanks for contributing!

Feedback:
- Rename section to *Artificial Intelligence*
- Alphabetic order for links

**Comment by dev-aritra** [comment]
Done, please review.

**Comment by luismts** [comment]
Thanks for contributing!

Feedback:

- Change section name "Vision" to "Articles". Main section name should be the topic.
- Change filename "AI-apps" to "AI"
- If you want to create sections about AI you should create a subsection inside "AI" section

**Comment by dev-aritra** [comment]
@luismts made the necessary changes, please review

**Pull request merged**
