### PR TITLE
[Migration] Add articles category

### PR DESCRIPTION
**Pull request by yauhenipakala**
:pencil2: **Articles**: 

By sending this pull request to contribute I verify that I adhere to the Xamarin Universal Library guidelines:

- [x] The pull request adheres to the repository's `Code of Conduct`.
- [x] I have followed the section's `Contributing Guidelines`.
- [x] I understand, `Titles` should be capitalized. I have checked the grammar.
- [x] I have searched for previous suggestions before making this new one, as mine could be a duplicate.
- [x] I understand, my contribution may be removed at any time if any of these guidelines are broken.
- [x] The submitted contribution is not owned by a company which sole purpose it is to advertise a product of product line.

Only the collaborators of this repository decide whether a contribution is eligible or not. They will determine if the rules are followed and if the quality of the content is high enough. 

Opening another PR, after the first one is closed in a small period of time will not be reevaluated. If a PR is closed, the issues with your contribution are too significant to be fixed within a matter of hours.

### CODE REVIEW

**Comment by luismts** [comment]
Here there are some many things to discuss. 

1. We don't want repetitive content in the library about the same topic.
1. We need to create filters to select the page that will describe the topic.
1. We need to separate concepts in order to not get a big list and improve the user experience. Here we need to create a separate file for each section.
1. The list of each section need to have at least "Title", "Description" or "Topics cover in the post" and "Language" properties in order to follow the structure of the library and user can easily understand the path.

**Comment by yauhenipakala** [comment]
Hi @luismts 

Example of separation by topics above.

I think it will be a good solution based on your thoughts above. And has consistency with other different sections (like books) in this repository.

What do you think about this?

**Comment by luismts** [comment]
Do you mean in the architecture topic? Yes, that actually the idea. But we must add the article's author and link it with his webpage. @wcoder

**Comment by luismts** [comment]
Excellent! Really good resources!!

**Pull request merged**
