### PR TITLE
Added xaml utilities in tools

### PR DESCRIPTION
**Pull request by dev-aritra**
:pencil2: **Section**:  Tools

By sending this pull request to contribute I verify that I adhere to the Xamarin Universal Library guidelines

- [x] The pull request adheres to the repository's `Code of Conduct`.
- [x] I have followed the section's `Contributing Guidelines`.
- [x] I understand, `Titles` should be capitalized. I have checked the grammar.
- [x] I have searched for previous suggestions before making this new one, as mine could be a duplicate.
- [x] I understand, my contribution may be removed at any time if any of these guidelines are broken.
- [x] The submitted contribution is not owned by a company which sole purpose it is to advertise a product or product line.

### CODE REVIEW

**Comment by luismts** [comment]
This section is out of the guidelines we set. We don't want to have a large list of everything. We need to rework on it.

**Comment by yauhenipakala** [comment]
Hi @dev-aritra 
Currently, you can create a new category `XAML Utilities` (in `tool-categories` folder, see already created categories for example)

**Comment by dev-aritra** [comment]
Done, please review.

**Review by yauhenipakala — COMMENTED** [review]
Looks good, thanks!

**Pull request merged**
