### PR TITLE
[Migration] Communities

### PR DESCRIPTION
**Pull request by yauhenipakala**
:pencil2: **Community**: 

By sending this pull request to contribute I verify that I adhere to the Xamarin Universal Library guidelines:

- [x] The pull request adheres to the repository's `Code of Conduct`.
- [x] I have followed the section's `Contributing Guidelines`.
- [x] I understand, `Titles` should be capitalized. I have checked the grammar.
- [x] I have searched for previous suggestions before making this new one, as mine could be a duplicate.
- [x] I understand, my contribution may be removed at any time if any of these guidelines are broken.
- [x] The submitted contribution is not owned by a company which sole purpose it is to advertise a product of product line.

Only the collaborators of this repository decide whether a contribution is eligible or not. They will determine if the rules are followed and if the quality of the content is high enough. 

Opening another PR, after the first one is closed in a small period of time will not be reevaluated. If a PR is closed, the issues with your contribution are too significant to be fixed within a matter of hours.

### CODE REVIEW

**Comment by luismts** [comment]
- The name "Xamarin Developers" doesn't match with the name of the community on Facebook. And "Xamarin Developers" community already exist. 

- The Xamarin Chat on slack is private. 

- Officials pages need to have "Official" in the name. I didn't put it but I will.

**Comment by yauhenipakala** [comment]
Fixed

**Comment by luismts** [comment]
"Xamarin Developers" and "Xamarin Developers Russia on Facebook" are Pages, not a community. "Official" need to be at the beginning. Sorry, too many rules, but they are necessary. 

Here you can see the "[Xamarin Developers](https://www.facebook.com/groups/xamarin.developers/)" community on Facebook.

**Comment by luismts** [comment]
You can add a section for pages if you realy like to add that page. It will be nice

**Comment by luismts** [comment]
Please before making a pull request, be sure all the info follow the correct structure. 

1. You should change "Xamarin Community Forums" for "Official Xamarin Forums".
1. The "Xamarin Developers Russia" Facebook link is a Page, not a community.

**Comment by yauhenipakala** [comment]
Yes, you are right! Fixed

What do you think, where create the section for community pages be better, on this page or on the separate?

**Comment by luismts** [comment]
We can create as a main section for Xamarin Pages.

**Comment by luismts** [comment]
Now, seems to be good.

**Pull request merged**
